jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

#spring:
#  batch:
#    jdbc:
#      initialize-schema: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

upload:
  solved:
    path: O:\Dev\nor3st-backend\src\main\resources\static\upload\solved\
  problem:
    path: O:\Dev\nor3st-backend\src\main\resources\static\upload\problems\

ai:
  url: http://192.168.50.32:80
#  url: http://221.163.19.218:5541
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


# Include external database configuration
spring.config.import: db-config.yml

spring:
  batch:
    job:
      enabled: false

server:
  port: 8080
